export const cardArray = [
    {
        id: 0,
        title: "Первый товар",
        price: "170 ₽",
        address: "Казань, р-н Вахитовский",
        date: "10 июля 11:39",
        image: "/image/card.png",
    },
    {
        id: 1,
        title: "Второй товар",
        price: "180 ₽",
        address: "Казань, р-н Вахитовский",
        date: "10 июля 11:39",
        image: "/image/card.png",
    },
    {
        id: 2,
        title: "Третий товар",
        price: "190 ₽",
        address: "Казань, р-н Вахитовский",
        date: "10 июля 11:39",
        image: "/image/card.png",
    },
    {
        id: 3,
        title: "Четвертый товар",
        price: "200 ₽",
        address: "Казань, р-н Вахитовский",
        date: "10 июля 11:39",
        image: "/image/card.png",
    },
    {
        id: 4,
        title: "Пятый товар",
        price: "300 ₽",
        address: "Казань, р-н Вахитовский",
        date: "10 июля 11:39",
        image: "/image/card.png",
    },
    {
        id: 5,
        title: "Шестой товар",
        price: "400 ₽",
        address: "Казань, р-н Вахитовский",
        date: "10 июля 11:39",
        image: "/image/card.png",
    },
]